version: '1'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    depends_on:
     - api
  api:
    build: ./api
    ports:
     - "8080:8080"
    depends_on:
     - blockchain
  blockchain:
    image: vechain/thor